version: '3.8'

networks:
  app:
    driver: bridge

services:
  database:
    build:
      dockerfile: packages/database/Dockerfile
      context: .
    restart: always
    networks:
      - app
    ports:
      - 5432:5432
    expose:
      - 5432

  backend:
    build:
      dockerfile: packages/backend/Dockerfile
      context: .
    networks:
      - app
    env_file:
      - packages/backend/.env
    ports:
      - ${BE_PORT}:${BE_PORT}
    expose:
      - ${BE_PORT}
    depends_on:
      - database

  frontend:
    build:
      dockerfile: packages/frontend/Dockerfile
      context: .
    networks:
      - app
    env_file:
      - packages/frontend/.env
    ports:
      - ${FE_PORT}:${FE_PORT}
    expose:
      - ${FE_PORT}
    depends_on:
      - backend
