version: '3.8'

networks:
  app:
    driver: bridge

services:
  backend:
    build:
      dockerfile: packages/backend/Dockerfile
      context: .
    networks:
      - app
    ports:
      - 3000:3000

  frontend:
    build:
      dockerfile: packages/frontend/Dockerfile
      context: .
    networks:
      - app
    ports:
      - 5173:5173
