version: '3.8'

networks:
  app:
    driver: bridge

services:
  database:
    build:
      dockerfile: packages/database/Dockerfile
      context: .
    restart: always
    networks:
      - app
    env_file:
      - .env
    ports:
      - ${POSTGRES_PORT}:5432
    expose:
      - ${POSTGRES_PORT}

  cache:
    build:
      dockerfile: packages/cache/Dockerfile
      context: .
      args:
        REDIS_USER: ${REDIS_USER}
        REDIS_PASS: ${REDIS_PASS}
        REDIS_PORT: ${REDIS_PORT}
    restart: always
    networks:
      - app
    env_file:
      - .env
    ports:
      - ${REDIS_PORT}:6379
    expose:
      - ${REDIS_PORT}

  backend:
    build:
      dockerfile: packages/backend/Dockerfile
      context: .
    networks:
      - app
    env_file:
      - .env
      - .env.production
    ports:
      - ${BE_PORT}:${BE_PORT}
    expose:
      - ${BE_PORT}
    depends_on:
      - database
      - cache

  frontend:
    build:
      dockerfile: packages/frontend/Dockerfile
      context: .
    networks:
      - app
    env_file:
      - .env
      - .env.production
    ports:
      - ${FE_PORT}:${FE_PORT}
    expose:
      - ${FE_PORT}
    depends_on:
      - backend
