version: '3.8'

networks:
  app:
    driver: bridge

services:
  database:
    build:
      dockerfile: packages/database/Dockerfile
      context: .
    restart: always
    networks:
      - app
    ports:
      - 5432:5432
    expose:
      - 5432

  backend:
    build:
      dockerfile: packages/backend/Dockerfile
      context: .
    networks:
      - app
    ports:
      - 3000:3000
    expose:
      - 3000
    depends_on:
      - database

  frontend:
    build:
      dockerfile: packages/frontend/Dockerfile
      context: .
    networks:
      - app
    ports:
      - 5173:5173
    expose:
      - 5173
    depends_on:
      - backend
